### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Pudellos**

### CODE REVIEW

**Review by JohnQuinn1 — CHANGES_REQUESTED** [review]
Looks good. Some changes I suggest:
1. the warning when the model name is not correct (Key error) should include the incorrect model name give to help with debugging.
2. the lower limit of 0.8 TeV is very high - I expect it should be < 100 GeV. I have just checked the Franceschini data files and it starts at 20 GeV.
3. sys.exit(1) is bad in a program that runs on a server! It will cause the entire python process to exit. I suggest if the energy is too low to simply give the warning and return 1 (all of the flux survives at low energies)
4. When running interactively on the command line errors should be printed to the screen so I suggest do not log to a file but leave it the default (stdout).
5. It would be good to add to the main program the ability to enter energy and redshift and have it print the surviving flux.

**Review by JohnQuinn1 — CHANGES_REQUESTED** [review]
Hi Klara,

You seem to have mixed two of my comments!

We should only use logging and never print in the library - I suggested add the name of the EBL model when it failed to the logging message.

Also, in the __main__ section you simply remove the filename='EBLAbsorption.log; and it will print to stdout (the screen!). That is what you want it to do when running interactively.

200 GeV for a threshold is too high! Franceschini is 20 GeV. We need to figure out what it is for each model!

John

**Comment by Pudellos** [comment]
Dear Professor John,
All right, now I only have logging that prints straight away, it doesn't
save anything to file. And if model is franceschini, it says that model is
franceschini and lowest energy is 20 GeV.
I tried reading the paper but it says "The corresponding high-energy
exponential cutoffs are customarily identified in the high- and very-high
energy (HE [0.2to 100 GeV] - and VHE [above 100 GeV])". I was trying to
make the gammapy display the minimum energy over which the models are valid
but I don't think it does this. I will try to find minimum energies of
models tomorrow. For now I attach my code here. It now needs the minimum
energies of models, which I don't know yet, so I think there's not much
point in trying to merge it on GitHub.

from gammapy.spectrum.models import Absorption
import astropy.units as u
import logging
import sys
ebllogger=logging.getLogger(__name__)
class EBLAbsorption:
    def __init__(self,model="franceschini"):
        self.model=model
        try:
            self.ebl=Absorption.read_builtin(str(self.model))
        except KeyError as error:
            ebllogger.warning(str(error)+"is an invalid name of model")
#             sys.exit(1)

    def absorption(self,redshift,energy):
        if self.model=="franceschini":
            if min(energy)<20*u.GeV:
                ebllogger.warning("energy out of range => too small. model
= franceschini, min energy = 20 GeV")
                return(1)
      (more code to be inserted here, for other models)
            else:
                return self.ebl.evaluate((energy),redshift)

    def get_flux(self,redshift,energy):
        return(self.absorption(redshift,energy)*energy)

#######################################################################

if __name__ == "__main__":

    logging.basicConfig(level=logging.WARNING,format='%(asctime)s
%(message)s', \
                   datefmt='%m/%d/%Y %I:%M:%S %p')

**Comment by JohnQuinn1** [comment]
Hi Klara,

Sending logging to screen when it is run on the command line and not logging to a file at all is exactly what we want. When it is loaded as a module by another program (e.g. on a server) it is up to that program to decide where the logging output is to go!

The minimum and maximum energy can be got from, for example:
finke=Absorption.read_builtin("finke")  
emin=min(finke.energy)
emax=max(finke.energy)

John

**Comment by JohnQuinn1** [comment]
we should also check the valid redshift range with:
minz=min(model.param)
maxz=max(model.param)

I checked the gammapy interpolation code and it has "extrapolate=True" set in the interpolator which is why we don't get an error when we to outside the range of the model!

**Comment by Pudellos** [comment]
Dear Professor John,
All right, so if I just somehow set extrapolate to False then this should
do the job, and I don;t need to go through coding the min energies, I'll
try to do this. There is a potential problems with the code:
it only takes tuples for energy, not a single value, eg. 1*u.GeV won't work
but (1 , 2)*u.GeV does work. Would you like it to be fixed or should I just
include it within exception and errors?

Klara

**Comment by JohnQuinn1** [comment]
Hi Klara,

It is set internally in the gammapy code so I would just check the max. and min. energies and redshifts in your code.

It would be good to be able to take single values and in your main program to be able to enter an E and z on the command line!

John

**Comment by Pudellos** [comment]
And does enterting parameters on command line mean that it requires argparse?

**Pull request merged**
